# Generated by Django 6.0.7 on 2026-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaLibre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
